/**************************************************************************/
/* Copyright (c) 2021 Qualcomm Technologies International, Ltd.           */
/* Autogenerated File, Do Not Edit                                        */
/*                                                                        */
/* This file exports public entry points from patch code                  */
/*                                                                        */
/**************************************************************************/
#ifndef SUBSYS3_PATCH0_FW00001BD0_MAP_PUBLIC_H
#define SUBSYS3_PATCH0_FW00001BD0_MAP_PUBLIC_H

#define PATCH_BUILD_ID                           17162

#define ENTRY_POINT_TTP_CONFIGURE_SP_ADJUSTMENT  0x040028c9 /* $_ttp_configure_sp_adjustment */
#define ENTRY_POINT_TTP_ADJUST_TTP_TIMESTAMP     0x040028db /* $_ttp_adjust_ttp_timestamp */
#define ENTRY_POINT_TTP_GET_MSG_STATE_PARAMS     0x040028f3 /* $_ttp_get_msg_state_params */
#define ENTRY_POINT_TTP_CONFIGURE_STATE_PARAMS   0x04002943 /* $_ttp_configure_state_params */
#define ENTRY_POINT_TTP_GET_STATE_PARAMS_STATUS  0x040029ef /* $_ttp_get_state_params_status */
#define ENTRY_POINT_GET_MSG_SP_ADJUSTMENT        0x040028ad /* $_ttp_get_msg_sp_adjustment */
#define ENTRY_POINT_TTP_GET_MSG_ADJUST_TTP_TIMESTAMP 0x040028bb /* $_ttp_get_msg_adjust_ttp_timestamp */
#define ENTRY_POINT_THREAD_OFFLOAD_UPDATE_P1_MEM_LOCATION 0x04002ca5 /* $_thread_offload_update_p1_mem_location */
#define ENTRY_POINT_STREAM_SHORT_DOWNSTREAM_PROBE 0x04004f69 /* $_stream_short_downstream_probe */
#define ENTRY_POINT_STREAM_CALC_DOWNSTREAM_AMOUNT_WORDS_EX 0x04004fe1 /* $_stream_calc_downstream_amount_words_ex */
#define ENTRY_POINT_STREAM_TRANSFORM_FROM_BUFFER 0x0400501f /* $_stream_transform_from_buffer */
#define ENTRY_POINT_CREATE_HOWLING_LIMITER_OP_PATCH 0x04006193 /* $_create_howling_limiter_op_patch */
#define ENTRY_POINT_INITIALIZE_HOWLING_LIMITER_OP_PATCH 0x040061cf /* $_initialize_howling_limiter_op_patch */
#define ENTRY_POINT_CONFIGURE_HOWLING_LIMITER_OP_PATCH 0x040061d9 /* $_configure_howling_limiter_op_patch */

#endif /* SUBSYS3_PATCH0_FW00001BD0_MAP_PUBLIC_H */
