/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The peer_link_keys marshal type declarations. This file is generated by C:/Qualcomm_Prog/qcc514x-qcc304x-src-1-0_qtil_standard_oem_earbud-ADK-21.1-CS2-MR1/adk/tools/packages/typegen/typegen.py.
*/

#ifndef _PEER_LINK_KEYS_MARSHAL_TYPEDEF_H__
#define _PEER_LINK_KEYS_MARSHAL_TYPEDEF_H__

#include <csrtypes.h>
#include <bdaddr.h>
#include <app/marshal/marshal_if.h>
#include <marshal_common.h>


#define PEER_LINK_KEYS_MARSHAL_TYPES_TABLE(ENTRY)\
    ENTRY(peer_link_keys_key_type_t)\
    ENTRY(peer_link_keys_add_key_req_t)\
    ENTRY(peer_link_keys_add_key_cfm_t)

#define EXPAND_AS_ENUMERATION(type) MARSHAL_TYPE(type),
enum PEER_LINK_KEYS_MARSHAL_TYPES
{
    DUMMY = (NUMBER_OF_COMMON_MARSHAL_OBJECT_TYPES-1),
    PEER_LINK_KEYS_MARSHAL_TYPES_TABLE(EXPAND_AS_ENUMERATION)
    NUMBER_OF_PEER_LINK_KEYS_MARSHAL_TYPES
} ;

#undef EXPAND_AS_ENUMERATION

extern const marshal_type_descriptor_t * const peer_link_keys_marshal_type_descriptors[];
#endif /* _PEER_LINK_KEYS_MARSHAL_TYPEDEF_H__ */

