/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The connection_manager_list marshal type definitions. This file is generated by C:/Qualcomm_Prog/QCC514x_304x_Earbud/adk/tools/packages/typegen/typegen.py.
*/

#include <csrtypes.h>
#include <marshal_common.h>
#include <task_list.h>
#include <connection_manager.h>
#include <link_policy.h>
#include <connection_no_ble.h>
#include <app/marshal/marshal_if.h>
#include <connection_manager_list_typedef.h>
#include <connection_manager_list_marshal_typedef.h>

#include "domain_marshal_types.h"

#ifndef HOSTED_TEST_ENVIRONMENT 	
COMPILE_TIME_ASSERT(sizeof(lp_power_mode) == sizeof(uint8), lp_power_mode_is_not_the_same_size_as_uint8);
#endif

const marshal_type_descriptor_t marshal_type_descriptor_cm_connection_state_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(cm_connection_state_t);
const marshal_type_descriptor_t marshal_type_descriptor_cm_con_bitfields_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(cm_con_bitfields_t);
const marshal_type_descriptor_t marshal_type_descriptor_cm_connection_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(cm_connection_t);


