/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The bandwidth_manager marshal type declarations. This file is generated by C:/Qualcomm_Prog/qcc514x-qcc304x-src-1-0_qtil_standard_oem_earbud-ADK-21.1-CS2-MR1/adk/tools/packages/typegen/typegen.py.
*/

#ifndef _BANDWIDTH_MANAGER_MARSHAL_TYPEDEF_H__
#define _BANDWIDTH_MANAGER_MARSHAL_TYPEDEF_H__

#include <csrtypes.h>
#include <marshal_common.h>
#include <bandwidth_manager.h>
#include <app/marshal/marshal_if.h>

extern const marshal_type_descriptor_t marshal_type_descriptor_feature_bitfields_t;
extern const marshal_type_descriptor_t marshal_type_descriptor_bandwidth_manager_feature_info_t;
extern const marshal_type_descriptor_dynamic_t marshal_type_descriptor_bandwidth_manager_info_t;

#define BANDWIDTH_MANAGER_MARSHAL_TYPES_TABLE(ENTRY)\
    ENTRY(feature_bitfields_t)\
    ENTRY(bandwidth_manager_feature_info_t)\
    ENTRY(bandwidth_manager_info_t)

#endif /* _BANDWIDTH_MANAGER_MARSHAL_TYPEDEF_H__ */

