/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The bandwidth_manager marshal type definitions. This file is generated by C:/Qualcomm_Prog/QCC514x_304x_Earbud/adk/tools/packages/typegen/typegen.py.
*/

#include <csrtypes.h>
#include <marshal_common.h>
#include <bandwidth_manager.h>
#include <app/marshal/marshal_if.h>
#include <bandwidth_manager_typedef.h>
#include <bandwidth_manager_marshal_typedef.h>

#include "domain_marshal_types.h"

extern uint32 BandwidthManager_ActiveFeaturesSize_cb(const void *parent,
                                     const marshal_member_descriptor_t *member_descriptor,
                                     uint32 array_element);

#ifdef HOSTED_TEST_ENVIRONMENT
uint32 BandwidthManager_ActiveFeaturesSize_cb(const void *parent,
                                     const marshal_member_descriptor_t *member_descriptor,
                                     uint32 array_element)
{

}
#endif

/*! The structure used to keep track of the registered features */
static const marshal_member_descriptor_t bandwidth_manager_feature_info_t_member_descriptors[] =
{
    /*! Bitfield attributes of feature */
    MAKE_MARSHAL_MEMBER(bandwidth_manager_feature_info_t, feature_bitfields_t, bitfields),
} ;

/*! The structure used to store bandwidth features information and its activity */
static const marshal_member_descriptor_t bandwidth_manager_info_t_member_descriptors[] =
{
    /*! Number of active features running */
    MAKE_MARSHAL_MEMBER(bandwidth_manager_info_t, uint8, active_features_num),
    /*! Array of feature information stored upon BandwidthManager_RegisterFeature */
    MAKE_MARSHAL_MEMBER_ARRAY(bandwidth_manager_info_t, bandwidth_manager_feature_info_t, feature_info, BANDWIDTH_MGR_FEATURE_MAX),
} ;

const marshal_type_descriptor_t marshal_type_descriptor_feature_bitfields_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(feature_bitfields_t);
const marshal_type_descriptor_t marshal_type_descriptor_bandwidth_manager_feature_info_t = MAKE_MARSHAL_TYPE_DEFINITION(bandwidth_manager_feature_info_t, bandwidth_manager_feature_info_t_member_descriptors);
const marshal_type_descriptor_dynamic_t marshal_type_descriptor_bandwidth_manager_info_t = MAKE_MARSHAL_TYPE_DEFINITION_HAS_DYNAMIC_ARRAY(bandwidth_manager_info_t, bandwidth_manager_info_t_member_descriptors, BandwidthManager_ActiveFeaturesSize_cb);


