/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from gatt_logging_server/gatt_logging_server_db.dbi_
 */
#ifndef __GATT_LOGGING_SERVER_DB_H
#define __GATT_LOGGING_SERVER_DB_H

#include <csrtypes.h>

#define HANDLE_LOGGING_SERVICE          (0x0001)
#define HANDLE_LOGGING_SERVICE_END      (0xffff)
#define HANDLE_LOGGING_REPORT           (0x0003)
#define HANDLE_LOGGING_CLIENT_CONFIG    (0x0004)
#define HANDLE_LOGGING_CONTROL          (0x0006)
#define HANDLE_LOGGING_DEBUG_CONFIGURATION (0x0008)

uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);
const uint16 *GattGetConstDatabase(uint16 *len);

#endif

/* End-of-File */
