/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The tws_topology c type definitions. This file is generated by C:/Qualcomm_Prog/qcc514x-qcc304x-src-1-0_qtil_standard_oem_earbud-ADK-21.1-CS2-MR1/adk/tools/packages/typegen/typegen.py.
*/

#ifndef _TWS_TOPOLOGY_TYPEDEF_H__
#define _TWS_TOPOLOGY_TYPEDEF_H__

#include <csrtypes.h>
#include <marshal_common.h>

typedef unsigned long long rule_event_t;

#define MARSHAL_TYPE_rule_event_t MARSHAL_TYPE_uint64

/*! Command to secondary to generate new rule event */
typedef struct 
{
    /*! Rule event to generate on Secondary */
    rule_event_t event;
} tws_topology_remote_rule_event_t;

#endif /* _TWS_TOPOLOGY_TYPEDEF_H__ */

