/* Copyright (c) 2021 Qualcomm Technologies International, Ltd. */
/*   %%version */
#ifndef IPC_BITSERIAL_SIGNAL_H_
#define IPC_BITSERIAL_SIGNAL_H_
#if TRAPSET_BITSERIAL
IPC_SIGNAL_ID_BITSERIAL_OPEN = 0x3b0000,
IPC_SIGNAL_ID_BITSERIAL_OPEN_RSP = 0x3b8000,
IPC_SIGNAL_ID_BITSERIAL_CLOSE = 0x3b0001,
IPC_SIGNAL_ID_BITSERIAL_CLOSE_RSP = 0x3b8001,
IPC_SIGNAL_ID_BITSERIAL_TRANSFER = 0x3b0003,
IPC_SIGNAL_ID_BITSERIAL_TRANSFER_RSP = 0x3b8003,
IPC_SIGNAL_ID_BITSERIAL_WRITE = 0x3b0004,
IPC_SIGNAL_ID_BITSERIAL_WRITE_RSP = 0x3b8004,
IPC_SIGNAL_ID_BITSERIAL_READ = 0x3b0005,
IPC_SIGNAL_ID_BITSERIAL_READ_RSP = 0x3b8005,
IPC_SIGNAL_ID_BITSERIAL_CHANGE_PARAM = 0x3b0006,
IPC_SIGNAL_ID_BITSERIAL_CHANGE_PARAM_RSP = 0x3b8006,
#endif /* TRAPSET_BITSERIAL */
#endif /* IPC_BITSERIAL_SIGNAL_H_ */
