/****************************************************************************
Copyright (c) 2016-2020 Qualcomm Technologies International, Ltd.
%%version

FILE NAME
    rsa_pss_constants.c

DESCRIPTION
    Constant data needed for the rsa_decrypt and the ce_pkcs1_pss_padding_verify
    function.

NOTES
    The constant data for the rsa_decrypt is generated by the host from the
    RSA public key and compiled into the CONFIG_HYDRACORE VM upgrade library.
    It is directly related to the RSA private and public key pair, and if they
    change then this file must be regenerated from the public key.

****************************************************************************/
#include "rsa_decrypt.h"

/*
 * The const rsa_mod_t *mod parameter for the rsa_decrypt function.
 */
const rsa_mod_t rsa_decrypt_constant_mod = {
    /* uint16 M[RSA_SIGNATURE_SIZE] where RSA_SIGNATURE_SIZE is 128 */
    {
        0xc5d9,     /* 00 */
        0x5a4a,     /* 01 */
        0x6894,     /* 02 */
        0x51f7,     /* 03 */
        0x5518,     /* 04 */
        0x3f10,     /* 05 */
        0xa5b1,     /* 06 */
        0xa0c9,     /* 07 */
        0x9710,     /* 08 */
        0xf084,     /* 09 */
        0x86ed,     /* 10 */
        0x64dc,     /* 11 */
        0xdb4a,     /* 12 */
        0x42b1,     /* 13 */
        0x3d84,     /* 14 */
        0x0df5,     /* 15 */
        0xd217,     /* 16 */
        0x00ad,     /* 17 */
        0x4a79,     /* 18 */
        0xde49,     /* 19 */
        0xbd81,     /* 20 */
        0x4690,     /* 21 */
        0x859a,     /* 22 */
        0xad47,     /* 23 */
        0x3e8a,     /* 24 */
        0x4634,     /* 25 */
        0x37d4,     /* 26 */
        0x652a,     /* 27 */
        0x8187,     /* 28 */
        0xcdab,     /* 29 */
        0xc6f0,     /* 30 */
        0xa5ed,     /* 31 */
        0x267f,     /* 32 */
        0x2b3d,     /* 33 */
        0x4d09,     /* 34 */
        0x4cae,     /* 35 */
        0xd829,     /* 36 */
        0xaf75,     /* 37 */
        0x1b07,     /* 38 */
        0x2529,     /* 39 */
        0xff20,     /* 40 */
        0x3101,     /* 41 */
        0xfe73,     /* 42 */
        0x2149,     /* 43 */
        0x83d9,     /* 44 */
        0xff9c,     /* 45 */
        0x705b,     /* 46 */
        0x4dcc,     /* 47 */
        0xf6cc,     /* 48 */
        0xa03c,     /* 49 */
        0x76f2,     /* 50 */
        0x317a,     /* 51 */
        0xc9a7,     /* 52 */
        0x840f,     /* 53 */
        0x0a20,     /* 54 */
        0x62ae,     /* 55 */
        0xcc6b,     /* 56 */
        0xa73b,     /* 57 */
        0xd6a9,     /* 58 */
        0x6ccb,     /* 59 */
        0xbdd0,     /* 60 */
        0x213b,     /* 61 */
        0x161a,     /* 62 */
        0x90a1,     /* 63 */
        0xa2b3,     /* 64 */
        0xd9fc,     /* 65 */
        0x85ee,     /* 66 */
        0xf9b3,     /* 67 */
        0x5ce9,     /* 68 */
        0x1fa0,     /* 69 */
        0x1e7f,     /* 70 */
        0x6a22,     /* 71 */
        0x6032,     /* 72 */
        0xd625,     /* 73 */
        0xf16c,     /* 74 */
        0x7c95,     /* 75 */
        0xd857,     /* 76 */
        0x80f9,     /* 77 */
        0x0804,     /* 78 */
        0xc86e,     /* 79 */
        0x2fd6,     /* 80 */
        0xb3a3,     /* 81 */
        0xa706,     /* 82 */
        0x421e,     /* 83 */
        0x9187,     /* 84 */
        0xc03c,     /* 85 */
        0xe23c,     /* 86 */
        0x785f,     /* 87 */
        0x3597,     /* 88 */
        0x22a2,     /* 89 */
        0x0bc2,     /* 90 */
        0x4c10,     /* 91 */
        0x3ab7,     /* 92 */
        0x4754,     /* 93 */
        0xfd53,     /* 94 */
        0x3ff1,     /* 95 */
        0x5bb6,     /* 96 */
        0x6266,     /* 97 */
        0x4be7,     /* 98 */
        0xdbd7,     /* 99 */
        0x1808,     /* 100 */
        0x6812,     /* 101 */
        0x0609,     /* 102 */
        0x5a7b,     /* 103 */
        0x26b9,     /* 104 */
        0x37f9,     /* 105 */
        0xd90c,     /* 106 */
        0xedfe,     /* 107 */
        0xe61e,     /* 108 */
        0x6b11,     /* 109 */
        0x7706,     /* 110 */
        0xadf4,     /* 111 */
        0xaf7b,     /* 112 */
        0x930b,     /* 113 */
        0x3832,     /* 114 */
        0xd004,     /* 115 */
        0xff6b,     /* 116 */
        0x3713,     /* 117 */
        0x074a,     /* 118 */
        0x0fa4,     /* 119 */
        0x9b4b,     /* 120 */
        0x8645,     /* 121 */
        0x5c62,     /* 122 */
        0x0a06,     /* 123 */
        0xdb0c,     /* 124 */
        0xefb2,     /* 125 */
        0x9e2b,     /* 126 */
        0xaa5d      /* 127 */
    },
    /* uint16 M_dash */
    0x860b
};

/* 
 * The "lump of memory passed in initialised to R^2N mod M" needed for the
 * uint16 *A parameter for the rsa_decrypt function. This must be copied into
 * a writable array of RSA_SIGNATURE_SIZE uint16 from here before use.
 */
const  uint16 rsa_decrypt_constant_sign_r2n[RSA_SIGNATURE_SIZE] = {
    0x29a1,     /* 00 */
    0xbcc1,     /* 01 */
    0xcd01,     /* 02 */
    0x7804,     /* 03 */
    0x0b05,     /* 04 */
    0x00c8,     /* 05 */
    0x65cf,     /* 06 */
    0xdb71,     /* 07 */
    0x6a57,     /* 08 */
    0x4cd3,     /* 09 */
    0x3527,     /* 10 */
    0xa2b7,     /* 11 */
    0xc590,     /* 12 */
    0xeceb,     /* 13 */
    0x65a8,     /* 14 */
    0xdf2f,     /* 15 */
    0x8535,     /* 16 */
    0x1152,     /* 17 */
    0xcaae,     /* 18 */
    0x7e19,     /* 19 */
    0x6ca1,     /* 20 */
    0xf073,     /* 21 */
    0x6f52,     /* 22 */
    0xe0e1,     /* 23 */
    0x9a5a,     /* 24 */
    0xa336,     /* 25 */
    0x5f18,     /* 26 */
    0x78d7,     /* 27 */
    0xbc9c,     /* 28 */
    0x2eda,     /* 29 */
    0xf6bc,     /* 30 */
    0x0c3b,     /* 31 */
    0xbcd7,     /* 32 */
    0x341d,     /* 33 */
    0x13ad,     /* 34 */
    0x2e64,     /* 35 */
    0x7517,     /* 36 */
    0x4899,     /* 37 */
    0xd705,     /* 38 */
    0xa831,     /* 39 */
    0xda71,     /* 40 */
    0x1e36,     /* 41 */
    0x591a,     /* 42 */
    0x56af,     /* 43 */
    0x539b,     /* 44 */
    0x2104,     /* 45 */
    0xe8c5,     /* 46 */
    0xcf59,     /* 47 */
    0x24a5,     /* 48 */
    0x03f0,     /* 49 */
    0x916b,     /* 50 */
    0x940b,     /* 51 */
    0xac9f,     /* 52 */
    0xd1f5,     /* 53 */
    0x24fc,     /* 54 */
    0x7ac7,     /* 55 */
    0xb09f,     /* 56 */
    0x7d69,     /* 57 */
    0x758f,     /* 58 */
    0x60c0,     /* 59 */
    0x78d7,     /* 60 */
    0x875e,     /* 61 */
    0xde18,     /* 62 */
    0x04db,     /* 63 */
    0x48be,     /* 64 */
    0xd375,     /* 65 */
    0xade4,     /* 66 */
    0x58e8,     /* 67 */
    0x4cbb,     /* 68 */
    0xe2dd,     /* 69 */
    0x21c4,     /* 70 */
    0xec6e,     /* 71 */
    0xf0da,     /* 72 */
    0xb1d0,     /* 73 */
    0x9b61,     /* 74 */
    0x7b9e,     /* 75 */
    0xbfb2,     /* 76 */
    0xd2f9,     /* 77 */
    0x2242,     /* 78 */
    0x7af8,     /* 79 */
    0x0aae,     /* 80 */
    0x97f2,     /* 81 */
    0xe09e,     /* 82 */
    0x38a6,     /* 83 */
    0xf0bb,     /* 84 */
    0x6134,     /* 85 */
    0xdff4,     /* 86 */
    0x7015,     /* 87 */
    0xa0c3,     /* 88 */
    0xeea6,     /* 89 */
    0x66ee,     /* 90 */
    0x530f,     /* 91 */
    0xf029,     /* 92 */
    0x8e70,     /* 93 */
    0xc1ae,     /* 94 */
    0x1570,     /* 95 */
    0x1057,     /* 96 */
    0x9d92,     /* 97 */
    0x2703,     /* 98 */
    0x2540,     /* 99 */
    0x5d3b,     /* 100 */
    0x16e9,     /* 101 */
    0xaf58,     /* 102 */
    0x08aa,     /* 103 */
    0x2b20,     /* 104 */
    0x2902,     /* 105 */
    0x6fa3,     /* 106 */
    0xffdb,     /* 107 */
    0x3832,     /* 108 */
    0x7533,     /* 109 */
    0x854b,     /* 110 */
    0x7498,     /* 111 */
    0x13d7,     /* 112 */
    0xa76a,     /* 113 */
    0x9670,     /* 114 */
    0x02ef,     /* 115 */
    0xe751,     /* 116 */
    0x5d16,     /* 117 */
    0xfeec,     /* 118 */
    0xcf84,     /* 119 */
    0xaab0,     /* 120 */
    0x6cfa,     /* 121 */
    0x19cd,     /* 122 */
    0x87ad,     /* 123 */
    0x5756,     /* 124 */
    0x0ae1,     /* 125 */
    0x6717,     /* 126 */
    0x3d38      /* 127 */
};

/*
 * The value to be provided for the saltlen parameter to the 
 * ce_pkcs1_pss_padding_verify function used to decode the PSS padded SHA-256
 * hash. It has to match the value that was used in the encoding process.
 */
const unsigned long ce_pkcs1_pss_padding_verify_constant_saltlen = 222;
