/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The earbud_gaia marshal type definitions. This file is generated by C:/Qualcomm_Prog/QCC514x_304x_Earbud/adk/tools/packages/typegen/typegen.py.
*/

#include <csrtypes.h>
#include <app/marshal/marshal_if.h>
#include <earbud_gaia_typedef.h>
#include <earbud_gaia_marshal_typedef.h>

const marshal_type_descriptor_t marshal_type_descriptor_earbud_gaia_request_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(earbud_gaia_request_t);
const marshal_type_descriptor_t marshal_type_descriptor_earbud_gaia_response_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(earbud_gaia_response_t);


#define EXPAND_AS_TYPE_DEFINITION(type) (const marshal_type_descriptor_t *)&marshal_type_descriptor_##type,
const marshal_type_descriptor_t * const earbud_gaia_marshal_type_descriptors[] =
{
    EARBUD_GAIA_MARSHAL_TYPES_TABLE(EXPAND_AS_TYPE_DEFINITION)
} ;

#undef EXPAND_AS_TYPE_DEFINITION

