/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The earbud_gaia c type definitions. This file is generated by C:/Qualcomm_Prog/QCC514x_304x_Earbud/adk/tools/packages/typegen/typegen.py.
*/

#ifndef _EARBUD_GAIA_TYPEDEF_H__
#define _EARBUD_GAIA_TYPEDEF_H__

#include <csrtypes.h>

/*! Data request to peer */
typedef struct 
{
    /*! Request context */
    uint32 context;
    /*! Request ID */
    uint8 request_id;
} earbud_gaia_request_t;

/*! Data response from peer */
typedef struct 
{
    /*! Request context */
    uint32 context;
    /*! Request ID */
    uint8 request_id;
    /*! Response status */
    uint8 status;
    /*! Size of response data */
    uint8 size_data;
    /*! Response data */
    uint8 data[32];
} earbud_gaia_response_t;

#endif /* _EARBUD_GAIA_TYPEDEF_H__ */

