/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The earbud_handover marshal type declarations. This file is generated by C:/Qualcomm_Prog/QCC514x_304x_Earbud/adk/tools/packages/typegen/typegen.py.
*/

#ifndef _EARBUD_HANDOVER_MARSHAL_TYPEDEF_H__
#define _EARBUD_HANDOVER_MARSHAL_TYPEDEF_H__

#include <csrtypes.h>
#include <marshal_common.h>
#include <app/marshal/marshal_if.h>

extern const marshal_type_descriptor_t marshal_type_descriptor_earbud_sm_timers;

#define EARBUD_HANDOVER_MARSHAL_TYPES_TABLE(ENTRY)\
    ENTRY(earbud_sm_timers)

#endif /* _EARBUD_HANDOVER_MARSHAL_TYPEDEF_H__ */

