/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_va_graph_manager.h
    \brief The chain_va_graph_manager chain.

    This file is generated by C:\Qualcomm_Prog\QCC514x_304x_Earbud\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_VA_GRAPH_MANAGER_H__
#define _CHAIN_VA_GRAPH_MANAGER_H__

/*!
\page chain_va_graph_manager
    @startuml
        object OPR_VA_GRAPH_MANAGER
        OPR_VA_GRAPH_MANAGER : id = CAP_ID_DOWNLOAD_VA_GRAPH_MANAGER
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_va_graph_manager_config;

#endif /* _CHAIN_VA_GRAPH_MANAGER_H__ */

