/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_tone_gen.c
    \brief The chain_tone_gen chain.

    This file is generated by C:\Qualcomm_Prog\QCC514x_304x_Earbud\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#include <chain_tone_gen.h>
#include <cap_id_prim.h>
#include <opmsg_prim.h>
#include <hydra_macros.h>
#include <../earbud_cap_ids.h>
#include <kymera_chain_roles.h>
static const operator_config_t operators[] =
{
    MAKE_OPERATOR_CONFIG(CAP_ID_RINGTONE_GENERATOR, OPR_TONE_GEN),
    MAKE_OPERATOR_CONFIG(CAP_ID_BASIC_PASS, OPR_TONE_PROMPT_PCM_BUFFER),
} ;

static const operator_endpoint_t outputs[] =
{
    {OPR_TONE_PROMPT_PCM_BUFFER, EPR_TONE_PROMPT_CHAIN_OUT, 0},
} ;

static const operator_connection_t connections[] =
{
    {OPR_TONE_GEN, 0, OPR_TONE_PROMPT_PCM_BUFFER, 0, 1},
} ;

const chain_config_t chain_tone_gen_config = {0, 0, operators, 2, NULL, 0, outputs, 1, connections, 1};

