/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_aanc.c
    \brief The chain_aanc chain.

    This file is generated by C:\Qualcomm_Prog\QCC514x_304x_Earbud\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#include <chain_aanc.h>
#include <cap_id_prim.h>
#include <opmsg_prim.h>
#include <hydra_macros.h>
#include <../earbud_cap_ids.h>
#include <kymera_chain_roles.h>
static const operator_config_t operators[] =
{
    MAKE_OPERATOR_CONFIG(EB_CAP_ID_ADAPTIVE_ANC_REF, OPR_AANC),
} ;

static const operator_endpoint_t inputs[] =
{
    {OPR_AANC, EPR_AANC_VOICE_DECTECTION_IN, 0},
    {OPR_AANC, EPR_AANC_FF_MIC_IN, 3},
    {OPR_AANC, EPR_AANC_ERR_MIC_IN, 2},
} ;

const chain_config_t chain_aanc_config = {1, 0, operators, 1, inputs, 3, NULL, 0, NULL, 0};

