/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_fit_test_mic_path.h
    \brief The chain_fit_test_mic_path chain.

    This file is generated by C:\Qualcomm_Prog\qcc514x-qcc304x-src-1-0_qtil_standard_oem_earbud-ADK-21.1-CS2-MR1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_FIT_TEST_MIC_PATH_H__
#define _CHAIN_FIT_TEST_MIC_PATH_H__

/*!
\page chain_fit_test_mic_path
    @startuml
        object OPR_FIT_TEST_BASIC_PT
        OPR_FIT_TEST_BASIC_PT : id = CAP_ID_BASIC_PASS
        object OPR_FIT_TEST
        OPR_FIT_TEST : id = EB_CAP_ID_EARBUD_FIT_TEST
        OPR_FIT_TEST "PLAYBACK_IN(0)"<-- "OUTPUT1(0)" OPR_FIT_TEST_BASIC_PT
        OPR_FIT_TEST "INT_MIC_IN(1)"<-- "OUTPUT2(1)" OPR_FIT_TEST_BASIC_PT
        object EPR_FIT_TEST_PLAYBACK_IN #lightgreen
        OPR_FIT_TEST_BASIC_PT "INPUT1(0)" <-- EPR_FIT_TEST_PLAYBACK_IN
        object EPR_FIT_TEST_INT_MIC_IN #lightgreen
        OPR_FIT_TEST_BASIC_PT "INPUT2(1)" <-- EPR_FIT_TEST_INT_MIC_IN
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_fit_test_mic_path_config;

#endif /* _CHAIN_FIT_TEST_MIC_PATH_H__ */

