/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_aanc_fbc.c
    \brief The chain_aanc_fbc chain.

    This file is generated by C:\Qualcomm_Prog\qcc514x-qcc304x-src-1-0_qtil_standard_oem_earbud-ADK-21.1-CS2-MR1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#include <chain_aanc_fbc.h>
#include <cap_id_prim.h>
#include <opmsg_prim.h>
#include <hydra_macros.h>
#include <../earbud_cap_ids.h>
#include <kymera_chain_roles.h>
static const operator_config_t operators[] =
{
    MAKE_OPERATOR_CONFIG(EB_CAP_ID_CVC_FBC, OPR_AANC_FBC_FF_MIC_PATH),
    MAKE_OPERATOR_CONFIG(EB_CAP_ID_CVC_FBC, OPR_AANC_FBC_ERR_MIC_PATH),
} ;

static const operator_endpoint_t inputs[] =
{
    {OPR_AANC_FBC_FF_MIC_PATH, EPR_AANC_FBC_FF_MIC_REF_IN, 0},
    {OPR_AANC_FBC_FF_MIC_PATH, EPR_AANC_FBC_FF_MIC_IN, 1},
    {OPR_AANC_FBC_ERR_MIC_PATH, EPR_AANC_FBC_ERR_MIC_REF_IN, 0},
    {OPR_AANC_FBC_ERR_MIC_PATH, EPR_AANC_FBC_ERR_MIC_IN, 1},
} ;

static const operator_endpoint_t outputs[] =
{
    {OPR_AANC_FBC_FF_MIC_PATH, EPR_AANC_FBC_FF_MIC_OUT, 0},
    {OPR_AANC_FBC_ERR_MIC_PATH, EPR_AANC_FBC_ERR_MIC_OUT, 0},
} ;

const chain_config_t chain_aanc_fbc_config = {1, 0, operators, 2, inputs, 4, outputs, 2, NULL, 0};

