/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_aanc_fbc.h
    \brief The chain_aanc_fbc chain.

    This file is generated by C:\Qualcomm_Prog\QCC514x_304x_Earbud\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_AANC_FBC_H__
#define _CHAIN_AANC_FBC_H__

/*!
\page chain_aanc_fbc
    @startuml
        object OPR_AANC_FBC_FF_MIC_PATH
        OPR_AANC_FBC_FF_MIC_PATH : id = EB_CAP_ID_CVC_FBC
        object OPR_AANC_FBC_ERR_MIC_PATH
        OPR_AANC_FBC_ERR_MIC_PATH : id = EB_CAP_ID_CVC_FBC
        object EPR_AANC_FBC_FF_MIC_REF_IN #lightgreen
        OPR_AANC_FBC_FF_MIC_PATH "REF_IN(0)" <-- EPR_AANC_FBC_FF_MIC_REF_IN
        object EPR_AANC_FBC_FF_MIC_IN #lightgreen
        OPR_AANC_FBC_FF_MIC_PATH "MIC_IN(1)" <-- EPR_AANC_FBC_FF_MIC_IN
        object EPR_AANC_FBC_ERR_MIC_REF_IN #lightgreen
        OPR_AANC_FBC_ERR_MIC_PATH "REF_IN(0)" <-- EPR_AANC_FBC_ERR_MIC_REF_IN
        object EPR_AANC_FBC_ERR_MIC_IN #lightgreen
        OPR_AANC_FBC_ERR_MIC_PATH "MIC_IN(1)" <-- EPR_AANC_FBC_ERR_MIC_IN
        object EPR_AANC_FBC_FF_MIC_OUT #lightblue
        EPR_AANC_FBC_FF_MIC_OUT <-- "MIC_OUT(0)" OPR_AANC_FBC_FF_MIC_PATH
        object EPR_AANC_FBC_ERR_MIC_OUT #lightblue
        EPR_AANC_FBC_ERR_MIC_OUT <-- "MIC_OUT(0)" OPR_AANC_FBC_ERR_MIC_PATH
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_aanc_fbc_config;

#endif /* _CHAIN_AANC_FBC_H__ */

