/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_va_encode_msbc.h
    \brief The chain_va_encode_msbc chain.

    This file is generated by C:\Qualcomm_Prog\qcc514x-qcc304x-src-1-0_qtil_standard_oem_earbud-ADK-21.1-CS2-MR1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_VA_ENCODE_MSBC_H__
#define _CHAIN_VA_ENCODE_MSBC_H__

/*!
\page chain_va_encode_msbc
    @startuml
        object OPR_MSBC_ENCODER
        OPR_MSBC_ENCODER : id = CAP_ID_ASYNC_WBS_ENC
        object EPR_VA_ENCODE_IN #lightgreen
        OPR_MSBC_ENCODER "IN(0)" <-- EPR_VA_ENCODE_IN
        object EPR_VA_ENCODE_OUT #lightblue
        EPR_VA_ENCODE_OUT <-- "OUT(0)" OPR_MSBC_ENCODER
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_va_encode_msbc_config;

#endif /* _CHAIN_VA_ENCODE_MSBC_H__ */

