/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_fit_test_mic_path.c
    \brief The chain_fit_test_mic_path chain.

    This file is generated by C:\Qualcomm_Prog\QCC514x_304x_Earbud\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#include <chain_fit_test_mic_path.h>
#include <cap_id_prim.h>
#include <opmsg_prim.h>
#include <hydra_macros.h>
#include <../earbud_cap_ids.h>
#include <kymera_chain_roles.h>
static const operator_config_t operators[] =
{
    MAKE_OPERATOR_CONFIG(CAP_ID_BASIC_PASS, OPR_FIT_TEST_BASIC_PT),
    MAKE_OPERATOR_CONFIG(EB_CAP_ID_EARBUD_FIT_TEST, OPR_FIT_TEST),
} ;

static const operator_endpoint_t inputs[] =
{
    {OPR_FIT_TEST_BASIC_PT, EPR_FIT_TEST_PLAYBACK_IN, 0},
    {OPR_FIT_TEST_BASIC_PT, EPR_FIT_TEST_INT_MIC_IN, 1},
} ;

static const operator_connection_t connections[] =
{
    {OPR_FIT_TEST_BASIC_PT, 0, OPR_FIT_TEST, 0, 1},
    {OPR_FIT_TEST_BASIC_PT, 1, OPR_FIT_TEST, 1, 1},
} ;

const chain_config_t chain_fit_test_mic_path_config = {1, 0, operators, 2, inputs, 2, NULL, 0, connections, 2};

