/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_input_aptx_adaptive_stereo_mix_q2q.c
    \brief The chain_input_aptx_adaptive_stereo_mix_q2q chain.

    This file is generated by C:\Qualcomm_Prog\QCC514x_304x_Earbud\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#include <chain_input_aptx_adaptive_stereo_mix_q2q.h>
#include <cap_id_prim.h>
#include <opmsg_prim.h>
#include <hydra_macros.h>
#include <../earbud_cap_ids.h>
#include <kymera_chain_roles.h>
static const operator_config_t operators_p0[] =
{
    MAKE_OPERATOR_CONFIG(CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER, OPR_SWITCHED_PASSTHROUGH_CONSUMER),
    MAKE_OPERATOR_CONFIG(EB_CAP_ID_APTX_ADAPTIVE_DECODE, OPR_APTX_ADAPTIVE_DECODER),
} ;

static const operator_config_t operators_p1[] =
{
    MAKE_OPERATOR_CONFIG(CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER, OPR_SWITCHED_PASSTHROUGH_CONSUMER),
    MAKE_OPERATOR_CONFIG_P1(EB_CAP_ID_APTX_ADAPTIVE_DECODE, OPR_APTX_ADAPTIVE_DECODER),
} ;

static const operator_endpoint_t inputs[] =
{
    {OPR_SWITCHED_PASSTHROUGH_CONSUMER, EPR_SINK_MEDIA, 0},
} ;

static const operator_endpoint_t outputs[] =
{
    {OPR_APTX_ADAPTIVE_DECODER, EPR_SOURCE_DECODED_PCM, 0},
} ;

static const operator_connection_t connections[] =
{
    {OPR_SWITCHED_PASSTHROUGH_CONSUMER, 0, OPR_APTX_ADAPTIVE_DECODER, 0, 1},
} ;

const chain_config_t chain_input_aptx_adaptive_stereo_mix_q2q_config_p0 = {0, 0, operators_p0, 2, inputs, 1, outputs, 1, connections, 1};

const chain_config_t chain_input_aptx_adaptive_stereo_mix_q2q_config_p1 = {0, 0, operators_p1, 2, inputs, 1, outputs, 1, connections, 1};

