/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_aanc.h
    \brief The chain_aanc chain.

    This file is generated by C:\Qualcomm_Prog\QCC514x_304x_Earbud\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_AANC_H__
#define _CHAIN_AANC_H__

/*!
\page chain_aanc
    @startuml
        object OPR_AANC
        OPR_AANC : id = EB_CAP_ID_ADAPTIVE_ANC_REF
        object EPR_AANC_VOICE_DECTECTION_IN #lightgreen
        OPR_AANC "PLAYBACK_IN(0)" <-- EPR_AANC_VOICE_DECTECTION_IN
        object EPR_AANC_FF_MIC_IN #lightgreen
        OPR_AANC "EXT_FF_MIC(3)" <-- EPR_AANC_FF_MIC_IN
        object EPR_AANC_ERR_MIC_IN #lightgreen
        OPR_AANC "INT_ERR_MIC(2)" <-- EPR_AANC_ERR_MIC_IN
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_aanc_config;

#endif /* _CHAIN_AANC_H__ */

