/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_aec.h
    \brief The chain_aec chain.

    This file is generated by C:\Qualcomm_Prog\QCC514x_304x_Earbud\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_AEC_H__
#define _CHAIN_AEC_H__

/*!
\page chain_aec
    @startuml
        object OPR_AEC
        OPR_AEC : id = CAP_ID_AEC_REF
        object EPR_AEC_INPUT1 #lightgreen
        OPR_AEC "INPUT1(0)" <-- EPR_AEC_INPUT1
        object EPR_AEC_INPUT2 #lightgreen
        OPR_AEC "INPUT2(1)" <-- EPR_AEC_INPUT2
        object EPR_AEC_MIC1_IN #lightgreen
        OPR_AEC "MIC1_IN(2)" <-- EPR_AEC_MIC1_IN
        object EPR_AEC_MIC2_IN #lightgreen
        OPR_AEC "MIC2_IN(3)" <-- EPR_AEC_MIC2_IN
        object EPR_AEC_MIC3_IN #lightgreen
        OPR_AEC "MIC3_IN(4)" <-- EPR_AEC_MIC3_IN
        object EPR_AEC_MIC4_IN #lightgreen
        OPR_AEC "MIC4_IN(5)" <-- EPR_AEC_MIC4_IN
        object EPR_AEC_REFERENCE_OUT #lightblue
        EPR_AEC_REFERENCE_OUT <-- "REFERENCE_OUT(0)" OPR_AEC
        object EPR_AEC_SPEAKER1_OUT #lightblue
        EPR_AEC_SPEAKER1_OUT <-- "SPEAKER1_OUT(1)" OPR_AEC
        object EPR_AEC_SPEAKER2_OUT #lightblue
        EPR_AEC_SPEAKER2_OUT <-- "SPEAKER2_OUT(2)" OPR_AEC
        object EPR_AEC_MIC1_OUT #lightblue
        EPR_AEC_MIC1_OUT <-- "MIC1_OUT(3)" OPR_AEC
        object EPR_AEC_MIC2_OUT #lightblue
        EPR_AEC_MIC2_OUT <-- "MIC2_OUT(4)" OPR_AEC
        object EPR_AEC_MIC3_OUT #lightblue
        EPR_AEC_MIC3_OUT <-- "MIC3_OUT(5)" OPR_AEC
        object EPR_AEC_MIC4_OUT #lightblue
        EPR_AEC_MIC4_OUT <-- "MIC4_OUT(6)" OPR_AEC
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_aec_config;

#endif /* _CHAIN_AEC_H__ */

