/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_music_processing.h
    \brief The chain_music_processing chain.

    This file is generated by C:\Qualcomm_Prog\qcc514x-qcc304x-src-1-0_qtil_standard_oem_earbud-ADK-21.1-CS2-MR1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_MUSIC_PROCESSING_H__
#define _CHAIN_MUSIC_PROCESSING_H__

/*!
\page chain_music_processing
    @startuml
        object OPR_ADD_HEADROOM
        OPR_ADD_HEADROOM : id = CAP_ID_BASIC_PASS
        object OPR_SPEAKER_EQ
        OPR_SPEAKER_EQ : id = CAP_ID_PEQ
        object OPR_REMOVE_HEADROOM
        OPR_REMOVE_HEADROOM : id = CAP_ID_BASIC_PASS
        OPR_SPEAKER_EQ "IN(0)"<-- "OUT(0)" OPR_ADD_HEADROOM
        OPR_REMOVE_HEADROOM "IN(0)"<-- "OUT(0)" OPR_SPEAKER_EQ
        object EPR_MUSIC_PROCESSING_IN_L #lightgreen
        OPR_ADD_HEADROOM "IN(0)" <-- EPR_MUSIC_PROCESSING_IN_L
        object EPR_MUSIC_PROCESSING_OUT_L #lightblue
        EPR_MUSIC_PROCESSING_OUT_L <-- "OUT(0)" OPR_REMOVE_HEADROOM
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_music_processing_config_p0;

extern const chain_config_t chain_music_processing_config_p1;

#endif /* _CHAIN_MUSIC_PROCESSING_H__ */

