/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_input_aac_stereo_mix.h
    \brief The chain_input_aac_stereo_mix chain.

    This file is generated by C:\Qualcomm_Prog\qcc514x-qcc304x-src-1-0_qtil_standard_oem_earbud-ADK-21.1-CS2-MR1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_INPUT_AAC_STEREO_MIX_H__
#define _CHAIN_INPUT_AAC_STEREO_MIX_H__

/*!
\page chain_input_aac_stereo_mix
    @startuml
        object OPR_RTP_DECODER
        OPR_RTP_DECODER : id = CAP_ID_RTP_DECODE
        object OPR_AAC_DECODER
        OPR_AAC_DECODER : id = EB_CAP_ID_AAC_DECODER
        object OPR_LEFT_RIGHT_MIXER
        OPR_LEFT_RIGHT_MIXER : id = CAP_ID_MIXER
        OPR_AAC_DECODER "IN(0)"<-- "OUT(0)" OPR_RTP_DECODER
        OPR_LEFT_RIGHT_MIXER "IN_L(0)"<-- "OUT_0(0)" OPR_AAC_DECODER
        OPR_LEFT_RIGHT_MIXER "IN_R(1)"<-- "OUT_1(1)" OPR_AAC_DECODER
        object EPR_SINK_MEDIA #lightgreen
        OPR_RTP_DECODER "IN(0)" <-- EPR_SINK_MEDIA
        object EPR_SOURCE_DECODED_PCM #lightblue
        EPR_SOURCE_DECODED_PCM <-- "OUT(0)" OPR_LEFT_RIGHT_MIXER
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_input_aac_stereo_mix_config_p0;

extern const chain_config_t chain_input_aac_stereo_mix_config_p1;

#endif /* _CHAIN_INPUT_AAC_STEREO_MIX_H__ */

