/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The peer_ui c type definitions. This file is generated by C:/Qualcomm_Prog/qcc514x-qcc304x-src-1-0_qtil_standard_oem_earbud-ADK-21.1-CS2-MR1/adk/tools/packages/typegen/typegen.py.
*/

#ifndef _PEER_UI_TYPEDEF_H__
#define _PEER_UI_TYPEDEF_H__

#include <csrtypes.h>
#include <peer_ui.h>
#include <peer_signalling.h>
#include <ui_inputs.h>
#include <marshal_common.h>

#define MARSHAL_TYPE_ui_input_t MARSHAL_TYPE_uint16

/*! Structure has ui_event and timestamp to send across to secondary */
typedef struct 
{
    /*! UI Indication type */
    uint16 indication_type;
    /*! UI Indication index */
    uint16 indication_index;
    /*! Absolute time in microseconds when UI Event should be handled in secondary EB */
    marshal_rtime_t timestamp;
} peer_ui_event_t;

/*! Structure has ui_input and timestamp to send across to secondary */
typedef struct 
{
    /*! UI input sent from Primary EB to Secondary EB */
    ui_input_t ui_input;
    /*! Absolute time in microseconds when UI Input should be handled in secondary EB */
    marshal_rtime_t timestamp;
    /*! Data to be sent over to Secondary */
    uint8 data;
} peer_ui_input_t;

#endif /* _PEER_UI_TYPEDEF_H__ */

