/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The hfp_profile c type definitions. This file is generated by C:/Qualcomm_Prog/QCC514x_304x_Earbud/adk/tools/packages/typegen/typegen.py.
*/

#ifndef _HFP_PROFILE_TYPEDEF_H__
#define _HFP_PROFILE_TYPEDEF_H__

#include <csrtypes.h>
#include <marshal_common.h>
#include <hfp.h>
#include <task_list.h>
#include <battery_monitor.h>
#include <voice_sources_list.h>
#include <source_param_types.h>
#include <hfp_profile_states_typedef.h>
#include <hfp_profile_states_marshal_typedef.h>

/*! Defines  */
#define HFP_SLC_STATUS_NOTIFY_LIST_INIT_CAPACITY 1
#define HFP_STATUS_NOTIFY_LIST_INIT_CAPACITY 6

#define MARSHAL_TYPE_hfp_wbs_codec_mask MARSHAL_TYPE_uint16
#define MARSHAL_TYPE_source_state_t MARSHAL_TYPE_uint8

/*! HFP task bitfields data structure */
typedef struct 
{
    /*! AG supports in-band ringing tone */
    unsigned in_band_ring:1;
    /*! Voice recognition is active */
    unsigned voice_recognition_active:1;
    /*! Voice recognition pending */
    unsigned voice_recognition_request:1;
    /*! Microphone mute is active */
    unsigned mute_active:1;
    /*! Caller ID is active */
    unsigned caller_id_active:1;
    /*! Flags indicating if we should connect/disconnect silently */
    unsigned flags:3;
    /*! Current call state */
    hfp_call_state call_state:4;
    /*! Flag indicating if we have accepted the call */
    unsigned call_accepted:1;
    /*! Flag indicating if ACL is encrypted */
    unsigned encrypted:1;
    /*! Flag indicating that ACL detach is pending */
    unsigned detach_pending:1;
    /*! Flag indicating the disconnect reason */
    unsigned disconnect_reason:4;
    /*! HF indicator assigned number */
    unsigned hf_indicator_assigned_num:2;
    /*! eSCO is connecting */
    unsigned esco_connecting:1;
    /*! Reconnect handset after faulty swb slc disconnect */
    unsigned reconnect_handset:1;
    /*! eSCO is disconnecting */
    unsigned esco_disconnecting:1;
} hfpTaskDataBitfields;

/*! HFP instance structure, contains all the information for an HFP connection */
typedef struct 
{
    /*! HFP task */
    TaskData task;
    /*! Current state */
    hfpState state;
    /*! HFP operation lock, used to serialise HFP operations */
    uint16 hfp_lock;
    /*! HFP bitfields data */
    hfpTaskDataBitfields bitfields;
    /*! Profile currently used */
    hfp_profile profile;
    /*! Bitmap of supported SCO packets by both headset and AG */
    uint16 sco_supported_packets;
    /*! Address of connected AG */
    bdaddr ag_bd_addr;
    /*! Sink for SCO, 0 if no SCO active */
    Sink sco_sink;
    /*! Sink for SLC */
    Sink slc_sink;
    /*! WB-Speech codec bit masks. */
    hfp_wbs_codec_mask codec;
    /*! Wesco reported for the link. */
    uint8 wesco;
    /*! Qualcomm Codec Mode ID Selected - If in Qualcomm Codec Extensions mode. */
    uint16 qce_codec_mode_id;
    /*! Tesco reported for the link. */
    uint8 tesco;
    /*! Routing state of the source. */
    source_state_t source_state;
} hfpInstanceTaskData;

#endif /* _HFP_PROFILE_TYPEDEF_H__ */

