/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The hfp_profile_states marshal type declarations. This file is generated by C:/Qualcomm_Prog/QCC514x_304x_Earbud/adk/tools/packages/typegen/typegen.py.
*/

#ifndef _HFP_PROFILE_STATES_MARSHAL_TYPEDEF_H__
#define _HFP_PROFILE_STATES_MARSHAL_TYPEDEF_H__

#include <csrtypes.h>
#include <marshal_common.h>
#include <app/marshal/marshal_if.h>

extern const marshal_type_descriptor_t marshal_type_descriptor_hfpState;

#define HFP_PROFILE_STATES_MARSHAL_TYPES_TABLE(ENTRY)\
    ENTRY(hfpState)

#endif /* _HFP_PROFILE_STATES_MARSHAL_TYPEDEF_H__ */

