/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from gatt_handler_db.db_
 */

#include <panic.h>
#include <string.h>
#include "gatt_handler_db.h"

/* Static GATT database */
const uint16 gattDatabase[] = {
    /* 0001: Primary Service 1801 */
    0x0002, 0x0118,
    /* 0002: Characteristic Declaration 2a05 */
    0x3005, 0x2003, 0x0005, 0x2a00,
    /* 0003:  */
    0xd000,
    /* 0004: Client Characteristic Configuration */
    0x6402, 0x0000,
    /* 0005: Characteristic Declaration 2b29 */
    0x3005, 0x0a06, 0x0029, 0x2b00,
    /* 0006: . */
    0xd401, 0x0000,
    /* 0007: Primary Service 1800 */
    0x0002, 0x0018,
    /* 0008: Characteristic Declaration 2a00 */
    0x3005, 0x0209, 0x0000, 0x2a00,
    /* 0009:  */
    0xd400,
    /* 000a: Characteristic Declaration 2a01 */
    0x3005, 0x020b, 0x0001, 0x2a00,
    /* 000b:  */
    0xd400,
    /* 000c: Primary Service 180a */
    0x0002, 0x0a18,
    /* 000d: Characteristic Declaration 2a29 */
    0x3005, 0x020e, 0x0029, 0x2a00,
    /* 000e: . */
    0xdc01, 0x0000,
    /* 000f: Characteristic Declaration 2a24 */
    0x3005, 0x0210, 0x0024, 0x2a00,
    /* 0010: . */
    0xdc01, 0x0000,
    /* 0011: Characteristic Declaration 2a25 */
    0x3005, 0x0212, 0x0025, 0x2a00,
    /* 0012: . */
    0xdc01, 0x0000,
    /* 0013: Characteristic Declaration 2a27 */
    0x3005, 0x0214, 0x0027, 0x2a00,
    /* 0014: . */
    0xdc01, 0x0000,
    /* 0015: Characteristic Declaration 2a26 */
    0x3005, 0x0216, 0x0026, 0x2a00,
    /* 0016: . */
    0xdc01, 0x0000,
    /* 0017: Characteristic Declaration 2a28 */
    0x3005, 0x0218, 0x0028, 0x2a00,
    /* 0018: . */
    0xdc01, 0x0000,
    /* 0019: Characteristic Declaration 2a23 */
    0x3005, 0x021a, 0x0023, 0x2a00,
    /* 001a: . */
    0xdc01, 0x0000,
    /* 001b: Characteristic Declaration 2a2a */
    0x3005, 0x021c, 0x002a, 0x2a00,
    /* 001c: . */
    0xdc01, 0x0000,
    /* 001d: Characteristic Declaration 2a50 */
    0x3005, 0x021e, 0x0050, 0x2a00,
    /* 001e: . */
    0xdc01, 0x0000,
    /* 001f: Primary Service 00001100-d102-11e1-9b23-00025b00a5a5 */
    0x0010, 0xa5a5, 0x005b, 0x0200, 0x239b, 0xe111, 0x02d1, 0x0011, 0x0000,
    /* 0020: Characteristic Declaration 00001101-d102-11e1-9b23-00025b00a5a5 */
    0x3013, 0x0821, 0x00a5, 0xa500, 0x5b02, 0x0023, 0x9be1, 0x1102, 0xd101, 0x1100, 0x0000,
    /* 0021: . */
    0xcd01, 0x0000,
    /* 0022: Characteristic Declaration 00001102-d102-11e1-9b23-00025b00a5a5 */
    0x3013, 0x1223, 0x00a5, 0xa500, 0x5b02, 0x0023, 0x9be1, 0x1102, 0xd102, 0x1100, 0x0000,
    /* 0023: . */
    0xcc01, 0x0000,
    /* 0024: Client Characteristic Configuration */
    0x6c00,
    /* 0025: Characteristic Declaration 00001103-d102-11e1-9b23-00025b00a5a5 */
    0x3053, 0x1626, 0x00a5, 0xa500, 0x5b02, 0x0023, 0x9be1, 0x1102, 0xd103, 0x1100, 0x0000,
    /* 0026: . */
    0xcd01, 0x0000,
    /* 0027: Client Characteristic Configuration */
    0x6c00,
    /* 0028: Primary Service fe2c */
    0x0002, 0x2cfe,
    /* 0029: Characteristic Declaration fe2c1233-8366-4814-8eb0-01de32100bea */
    0x3013, 0x022a, 0x00ea, 0x0b10, 0x32de, 0x01b0, 0x8e14, 0x4866, 0x8333, 0x122c, 0xfe00,
    /* 002a: .. */
    0xcc02, 0x0000,
    /* 002b: Characteristic Declaration fe2c1234-8366-4814-8eb0-01de32100bea */
    0x3013, 0x282c, 0x00ea, 0x0b10, 0x32de, 0x01b0, 0x8e14, 0x4866, 0x8334, 0x122c, 0xfe00,
    /* 002c: .. */
    0xcc02, 0x0000,
    /* 002d: Client Characteristic Configuration */
    0x6402, 0x0000,
    /* 002e: Characteristic Declaration fe2c1235-8366-4814-8eb0-01de32100bea */
    0x3013, 0x282f, 0x00ea, 0x0b10, 0x32de, 0x01b0, 0x8e14, 0x4866, 0x8335, 0x122c, 0xfe00,
    /* 002f: .. */
    0xcc02, 0x0000,
    /* 0030: Client Characteristic Configuration */
    0x6402, 0x0000,
    /* 0031: Characteristic Declaration fe2c1236-8366-4814-8eb0-01de32100bea */
    0x3013, 0x0832, 0x00ea, 0x0b10, 0x32de, 0x01b0, 0x8e14, 0x4866, 0x8336, 0x122c, 0xfe00,
    /* 0032: .. */
    0xcc02, 0x0000,
    /* 0033: Characteristic Declaration fe2c1237-8366-4814-8eb0-01de32100bea */
    0x3013, 0x2834, 0x00ea, 0x0b10, 0x32de, 0x01b0, 0x8e14, 0x4866, 0x8337, 0x122c, 0xfe00,
    /* 0034: .. */
    0xcc02, 0x0000,
    /* 0035: Client Characteristic Configuration */
    0x6402, 0x0000,
    /* 0036: Characteristic Declaration 2a26 */
    0x3005, 0x0237, 0x0026, 0x2a00,
    /* 0037: .. */
    0xdc02, 0x0000,
    /* 0038: Primary Service 0000eb10-d102-11e1-9b23-00025b00a5a5 */
    0x0010, 0xa5a5, 0x005b, 0x0200, 0x239b, 0xe111, 0x02d1, 0x10eb, 0x0000,
    /* 0039: Characteristic Declaration 0000eb11-d102-11e1-9b23-00025b00a5a5 */
    0x3053, 0x023a, 0x00a5, 0xa500, 0x5b02, 0x0023, 0x9be1, 0x1102, 0xd111, 0xeb00, 0x0000,
    /* 003a: .. */
    0xc402, 0x0000,
    /* 003b: Characteristic Declaration 0000eb12-d102-11e1-9b23-00025b00a5a5 */
    0x3053, 0x023c, 0x00a5, 0xa500, 0x5b02, 0x0023, 0x9be1, 0x1102, 0xd112, 0xeb00, 0x0000,
    /* 003c: . */
    0xc401, 0x0000,
    /* 003d: Characteristic Declaration 0000eb13-d102-11e1-9b23-00025b00a5a5 */
    0x3013, 0x283e, 0x00a5, 0xa500, 0x5b02, 0x0023, 0x9be1, 0x1102, 0xd113, 0xeb00, 0x0000,
    /* 003e: . */
    0xcd01, 0x0000,
    /* 003f: Client Characteristic Configuration */
    0x6c00,
    /* 0040: Characteristic Declaration 0000eb14-d102-11e1-9b23-00025b00a5a5 */
    0x3013, 0x0841, 0x00a5, 0xa500, 0x5b02, 0x0023, 0x9be1, 0x1102, 0xd114, 0xeb00, 0x0000,
    /* 0041: . */
    0xcd01, 0x0000,
    /* 0042: Primary Service fd92 */
    0x0002, 0x92fd,
    /* 0043: Characteristic Declaration 0000eb20-d102-11e1-9b23-00025b00a5a5 */
    0x3053, 0x1244, 0x00a5, 0xa500, 0x5b02, 0x0023, 0x9be1, 0x1102, 0xd120, 0xeb00, 0x0000,
    /* 0044: . */
    0xc401, 0x0000,
    /* 0045: Client Characteristic Configuration */
    0x6c00,
    /* 0046: Characteristic Declaration 0000eb21-d102-11e1-9b23-00025b00a5a5 */
    0x3013, 0x0847, 0x00a5, 0xa500, 0x5b02, 0x0023, 0x9be1, 0x1102, 0xd121, 0xeb00, 0x0000,
    /* 0047: . */
    0xcd01, 0x0000,
    /* 0048: Characteristic Declaration 0000eb22-d102-11e1-9b23-00025b00a5a5 */
    0x3053, 0x1249, 0x00a5, 0xa500, 0x5b02, 0x0023, 0x9be1, 0x1102, 0xd122, 0xeb00, 0x0000,
    /* 0049: .. */
    0xc402, 0x0000,
    /* 004a: Client Characteristic Configuration */
    0x6c00,
    /* 004b: Primary Service 180f */
    0x0002, 0x0f18,
    /* 004c: Characteristic Declaration 2a19 */
    0x3005, 0x124d, 0x0019, 0x2a00,
    /* 004d: . */
    0xd401, 0x0000,
    /* 004e: Characteristic Presentation Format, rfu, 0 */
    0x8c07, 0x0000, 0x0000, 0x0000, 0x0000,
    /* 004f: Client Characteristic Configuration */
    0x6c00,
    /* 0050: Primary Service 180f */
    0x0002, 0x0f18,
    /* 0051: Characteristic Declaration 2a19 */
    0x3005, 0x1252, 0x0019, 0x2a00,
    /* 0052: . */
    0xd401, 0x0000,
    /* 0053: Characteristic Presentation Format, rfu, 0 */
    0x8c07, 0x0000, 0x0000, 0x0000, 0x0000,
    /* 0054: Client Characteristic Configuration */
    0x6c00,
};

/* SDP service snippets */
const uint8 gatt_sdp_class[] = {
    /* UINT16: ServiceClassIDList 0x0001 */
    0x09, 0x00, 0x01, 0x35, /* add length + type + UUID */
};

const uint8 gatt_sdp_prot[] = {
    /* UINT16: ProtocolDescriptorList 0x0004 */
    0x09, 0x00, 0x04,
    /* Segment: 19 bytes */
    0x35, 0x13,
    /** Segment: 6 bytes */
    /**/ 0x35, 0x06,
    /**** UUID16: L2CAP */
    /****/ 0x19, 0x01, 0x00,
    /**** UINT16: ATT PSM */
    /****/ 0x09, 0x00, 0x1f,
    /** Segment: 9 bytes */
    /**/ 0x35, 0x09,
    /**** UUID16: ATT */
    /****/ 0x19, 0x00, 0x07,
    /**** UINT16: start handle, to be filled later */
    /****/ 0x09, 0x00, 0x00,
    /**** UINT16: end handle, to be filled later */
    /****/ 0x09, 0x00, 0x00,

    /* UINT16: BrowseGroupList 0x0005 */
    0x09, 0x00, 0x05,
    /* Segment: 3 bytes */
    0x35, 0x03,
    /** UUID16: PublicBroseGroup */
    /**/ 0x19, 0x10, 0x02  
};

#define OFFS_START      0x0013  /* offset to starting handle */
#define OFFS_END        0x0016  /* offset to ending handle */

#define UUID_IS_16      0x0000  /* flag indicating 16-bit UUID */
#define UUID_IS_32      0x4000  /* flag indicating 32-bit UUID */
#define UUID_IS_128     0x8000  /* flag indicating 128-bit UUID */

/* DataElement Header for UUID16 (Type:0b00011 Size:0b001)
 * See Core V4.0 SDP Specification P221 Sec 3.2 & 3.3 */
#define SDP_UUID16      0x19
/* DataElement Header for UUID32 (Type:0b00011 Size:0b010)
 * See Core V4.0 SDP Specification P221 Sec 3.2 & 3.3 */
#define SDP_UUID32      0x1A
/* DataElement Header for UUID128 (Type:0b00011 Size:0b100)
 * See Core V4.0 SDP Specification P221 Sec 3.2 & 3.3 */
#define SDP_UUID128     0x1c

const struct 
{
    uint16      offs;
    uint16      start;
    uint16      end;
} sdp_data[] = {
    { UUID_IS_16  | 0x0010, 0x0007, 0x000b },     /* GAP_SERVICE */
    { UUID_IS_16  | 0x001c, 0x000c, 0x001e },     /* DEVICE_INFORMATION_SERVICE */
    { UUID_IS_16  | 0x013e, 0x004b, 0x004f },     /* BATTERY_SERVICE1 */
    { UUID_IS_16  | 0x014c, 0x0050, 0xffff },     /* BATTERY_SERVICE2 */
};

uint8 *GattGetServiceRecord(gatt_sdp service, uint16 *len)
{
    uint8 *sdp;
    uint8 *p_sdp;
    uint16 uuidlen;
    uint16 offs;

    if (service == gatt_sdp_last)
    {
        *len = 0U;
        return NULL;
    }

    if (sdp_data[service].offs & UUID_IS_128)
        /* 128-bit UUID */
    {
        /* 16 octets */
        uuidlen = 16U;
    }
    else if (sdp_data[service].offs & UUID_IS_32)
        /* 32-bit UUID */
    {
        /* 4 octets */
        uuidlen = 4U;
    }
    else
        /* 16-bit UUID */
    {
        /* 2 octets */
        uuidlen = 2U;
    }
    
    /* allocate memory */
    *len = sizeof(gatt_sdp_class) + sizeof(gatt_sdp_prot) + 2 + uuidlen ;
    sdp = PanicUnlessMalloc(*len);

    memmove(sdp, gatt_sdp_class, sizeof(gatt_sdp_class));
    p_sdp = &sdp[sizeof(gatt_sdp_class)];
    *p_sdp++ = uuidlen + 1;
    if ( sdp_data[service].offs & UUID_IS_128 )
    {
        *p_sdp++ = SDP_UUID128;
    }
    else if ( sdp_data[service].offs & UUID_IS_32 )
    {
        *p_sdp++ = SDP_UUID32;
    }
    else
    {
        *p_sdp++ = SDP_UUID16;
    }

    /* extract the UUID from the ATT database data */
    for (offs = ( sdp_data[service].offs
            & ~( UUID_IS_128 | UUID_IS_32 | UUID_IS_16 ) ); uuidlen; offs--)
    {
	/* The values below are explictly converted to 8-bits by zeroing of higher bytes, 
	 * as on bluecore uint8 is not necessarily 8-bits */	    
        *p_sdp++ = ( gattDatabase[offs] & 0xFF );
        *p_sdp++ = ( gattDatabase[offs] >> 8 ) & 0xFF;
        uuidlen -= 2;
    }

    memmove(p_sdp, gatt_sdp_prot, sizeof(gatt_sdp_prot));
    p_sdp[OFFS_START] = sdp_data[service].start >> 8;
    p_sdp[OFFS_START + 1] = sdp_data[service].start;
    p_sdp[OFFS_END] = sdp_data[service].end >> 8;
    p_sdp[OFFS_END + 1] = sdp_data[service].end;

    return sdp;
}

uint16 *GattGetDatabase(uint16 *len)
{
    uint16 *rc = PanicUnlessMalloc(sizeof(gattDatabase));
    *len = sizeof(gattDatabase);
    memmove(rc, gattDatabase, sizeof(gattDatabase));
    return rc;
}

uint16 GattGetDatabaseSize(void)
{
    return sizeof(gattDatabase);
}

const uint16 *GattGetConstDatabase(uint16 *len)
{
    *len = sizeof(gattDatabase);
    return gattDatabase;
}

/* End-of-File */
