/*!
\copyright  Copyright (c) 2020 Qualcomm Technologies International, Ltd.\n
            All Rights Reserved.\n
            Qualcomm Technologies International, Ltd. Confidential and Proprietary.
\version    
\file       gatt_handler_db_if.c
\defgroup   gatt_handler_db
\brief      This implements an interface to allow common code to access application
            specific GATT database service constants.
*/

/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by dbgen_interface_generator.py
 */

#include <csrtypes.h>
#include <logging.h>
#include <panic.h>

#include "gatt_handler_db.h"
#include "gatt_handler_db_if.h"

uint16 getGattAttributeValue(gatt_attribute_t id, uint16 n)
{
    switch ( id )
    {
#ifdef HAVEDB_HANDLE_BATTERY_SERVICE_END
        case handle_battery_service_end:
            if ( n == 1 ) return HANDLE_BATTERY_SERVICE1_END;
            if ( n == 2 ) return HANDLE_BATTERY_SERVICE2_END;
#endif
#ifdef HAVEDB_HANDLE_GATT_SERVICE
        case handle_gatt_service:
            return HANDLE_GATT_SERVICE;
#endif
#ifdef HAVEDB_HANDLE_MODEL_NUMBER
        case handle_model_number:
            return HANDLE_MODEL_NUMBER;
#endif
#ifdef HAVEDB_HANDLE_GAIA_RESPONSE_CLIENT_CONFIG
        case handle_gaia_response_client_config:
            return HANDLE_GAIA_RESPONSE_CLIENT_CONFIG;
#endif
#ifdef HAVEDB_HANDLE_FIRMWARE_REVISION
        case handle_firmware_revision:
            return HANDLE_FIRMWARE_REVISION;
#endif
#ifdef HAVEDB_HANDLE_SERIAL_NUMBER
        case handle_serial_number:
            return HANDLE_SERIAL_NUMBER;
#endif
#ifdef HAVEDB_HANDLE_BATTERY_LEVEL
        case handle_battery_level:
            if ( n == 1 ) return HANDLE_BATTERY_LEVEL1;
            if ( n == 2 ) return HANDLE_BATTERY_LEVEL2;
#endif
#ifdef HAVEDB_HANDLE_GATT_SERVICE_END
        case handle_gatt_service_end:
            return HANDLE_GATT_SERVICE_END;
#endif
#ifdef HAVEDB_HANDLE_ADK_FIRMWARE_REVISION
        case handle_adk_firmware_revision:
            return HANDLE_ADK_FIRMWARE_REVISION;
#endif
#ifdef HAVEDB_HANDLE_GAP_SERVICE_END
        case handle_gap_service_end:
            return HANDLE_GAP_SERVICE_END;
#endif
#ifdef HAVEDB_HANDLE_DEVICE_INFORMATION_SERVICE
        case handle_device_information_service:
            return HANDLE_DEVICE_INFORMATION_SERVICE;
#endif
#ifdef HAVEDB_HANDLE_BATTERY_LEVEL_PRESENTATION
        case handle_battery_level_presentation:
            if ( n == 1 ) return HANDLE_BATTERY_LEVEL_PRESENTATION1;
            if ( n == 2 ) return HANDLE_BATTERY_LEVEL_PRESENTATION2;
#endif
#ifdef HAVEDB_HANDLE_GAIA_RESPONSE_ENDPOINT
        case handle_gaia_response_endpoint:
            return HANDLE_GAIA_RESPONSE_ENDPOINT;
#endif
#ifdef HAVEDB_HANDLE_ROOT_TRANSFER_SERVICE_MIRROR_CONTROL_POINT
        case handle_root_transfer_service_mirror_control_point:
            return HANDLE_ROOT_TRANSFER_SERVICE_MIRROR_CONTROL_POINT;
#endif
#ifdef HAVEDB_HANDLE_SYSTEM_ID
        case handle_system_id:
            return HANDLE_SYSTEM_ID;
#endif
#ifdef HAVEDB_HANDLE_BATTERY_SERVICE
        case handle_battery_service:
            if ( n == 1 ) return HANDLE_BATTERY_SERVICE1;
            if ( n == 2 ) return HANDLE_BATTERY_SERVICE2;
#endif
#ifdef HAVEDB_HANDLE_GAIA_COMMAND_ENDPOINT
        case handle_gaia_command_endpoint:
            return HANDLE_GAIA_COMMAND_ENDPOINT;
#endif
#ifdef HAVEDB_HANDLE_ROOT_TRANSFER_SERVICE_STATUS
        case handle_root_transfer_service_status:
            return HANDLE_ROOT_TRANSFER_SERVICE_STATUS;
#endif
#ifdef HAVEDB_HANDLE_FAST_PAIR_SERVICE
        case handle_fast_pair_service:
            return HANDLE_FAST_PAIR_SERVICE;
#endif
#ifdef HAVEDB_HANDLE_PASSKEY_CLIENT_CONFIG
        case handle_passkey_client_config:
            return HANDLE_PASSKEY_CLIENT_CONFIG;
#endif
#ifdef HAVEDB_HANDLE_ROLE_SELECTION_SERVICE
        case handle_role_selection_service:
            return HANDLE_ROLE_SELECTION_SERVICE;
#endif
#ifdef HAVEDB_HANDLE_MANUFACTURER_NAME
        case handle_manufacturer_name:
            return HANDLE_MANUFACTURER_NAME;
#endif
#ifdef HAVEDB_HANDLE_PASSKEY
        case handle_passkey:
            return HANDLE_PASSKEY;
#endif
#ifdef HAVEDB_HANDLE_GAIA_DATA_ENDPOINT
        case handle_gaia_data_endpoint:
            return HANDLE_GAIA_DATA_ENDPOINT;
#endif
#ifdef HAVEDB_HANDLE_GATT_CLIENT_SUPPORTED_FEATURES
        case handle_gatt_client_supported_features:
            return HANDLE_GATT_CLIENT_SUPPORTED_FEATURES;
#endif
#ifdef HAVEDB_HANDLE_SOFTWARE_REVISION
        case handle_software_revision:
            return HANDLE_SOFTWARE_REVISION;
#endif
#ifdef HAVEDB_HANDLE_GATT_SERVICE_CHANGED
        case handle_gatt_service_changed:
            return HANDLE_GATT_SERVICE_CHANGED;
#endif
#ifdef HAVEDB_HANDLE_ACCOUNT_KEY
        case handle_account_key:
            return HANDLE_ACCOUNT_KEY;
#endif
#ifdef HAVEDB_HANDLE_DATA_CLIENT_CONFIG
        case handle_data_client_config:
            return HANDLE_DATA_CLIENT_CONFIG;
#endif
#ifdef HAVEDB_HANDLE_ROLE_SELECTION_CONTROL
        case handle_role_selection_control:
            return HANDLE_ROLE_SELECTION_CONTROL;
#endif
#ifdef HAVEDB_HANDLE_FAST_PAIR_SERVICE_END
        case handle_fast_pair_service_end:
            return HANDLE_FAST_PAIR_SERVICE_END;
#endif
#ifdef HAVEDB_HANDLE_ROOT_TRANSFER_SERVICE_END
        case handle_root_transfer_service_end:
            return HANDLE_ROOT_TRANSFER_SERVICE_END;
#endif
#ifdef HAVEDB_HANDLE_DEVICE_NAME
        case handle_device_name:
            return HANDLE_DEVICE_NAME;
#endif
#ifdef HAVEDB_HANDLE_PNP_ID
        case handle_pnp_id:
            return HANDLE_PNP_ID;
#endif
#ifdef HAVEDB_HANDLE_DEVICE_INFORMATION_SERVICE_END
        case handle_device_information_service_end:
            return HANDLE_DEVICE_INFORMATION_SERVICE_END;
#endif
#ifdef HAVEDB_HANDLE_KEYBASED_PAIRING_CLIENT_CONFIG
        case handle_keybased_pairing_client_config:
            return HANDLE_KEYBASED_PAIRING_CLIENT_CONFIG;
#endif
#ifdef HAVEDB_HANDLE_GAIA_SERVICE
        case handle_gaia_service:
            return HANDLE_GAIA_SERVICE;
#endif
#ifdef HAVEDB_HANDLE_BATTERY_LEVEL_CLIENT_CONFIG
        case handle_battery_level_client_config:
            if ( n == 1 ) return HANDLE_BATTERY_LEVEL_CLIENT_CONFIG1;
            if ( n == 2 ) return HANDLE_BATTERY_LEVEL_CLIENT_CONFIG2;
#endif
#ifdef HAVEDB_HANDLE_KEYBASED_PAIRING
        case handle_keybased_pairing:
            return HANDLE_KEYBASED_PAIRING;
#endif
#ifdef HAVEDB_HANDLE_ROOT_TRANSFER_SERVICE_KEYS_CONTROL
        case handle_root_transfer_service_keys_control:
            return HANDLE_ROOT_TRANSFER_SERVICE_KEYS_CONTROL;
#endif
#ifdef HAVEDB_HANDLE_ROLE_SELECTION_FIGURE_OF_MERIT_CLIENT_CONFIG
        case handle_role_selection_figure_of_merit_client_config:
            return HANDLE_ROLE_SELECTION_FIGURE_OF_MERIT_CLIENT_CONFIG;
#endif
#ifdef HAVEDB_HANDLE_ROLE_SELECTION_MIRRORING_STATE_CLIENT_CONFIG
        case handle_role_selection_mirroring_state_client_config:
            return HANDLE_ROLE_SELECTION_MIRRORING_STATE_CLIENT_CONFIG;
#endif
#ifdef HAVEDB_HANDLE_HARDWARE_REVISION
        case handle_hardware_revision:
            return HANDLE_HARDWARE_REVISION;
#endif
#ifdef HAVEDB_HANDLE_GAP_SERVICE
        case handle_gap_service:
            return HANDLE_GAP_SERVICE;
#endif
#ifdef HAVEDB_HANDLE_ROLE_SELECTION_FIGURE_OF_MERIT
        case handle_role_selection_figure_of_merit:
            return HANDLE_ROLE_SELECTION_FIGURE_OF_MERIT;
#endif
#ifdef HAVEDB_HANDLE_GAIA_SERVICE_END
        case handle_gaia_service_end:
            return HANDLE_GAIA_SERVICE_END;
#endif
#ifdef HAVEDB_HANDLE_IEEE_DATA
        case handle_ieee_data:
            return HANDLE_IEEE_DATA;
#endif
#ifdef HAVEDB_HANDLE_ROLE_SELECTION_MIRRORING_STATE
        case handle_role_selection_mirroring_state:
            return HANDLE_ROLE_SELECTION_MIRRORING_STATE;
#endif
#ifdef HAVEDB_HANDLE_DEVICE_APPEARANCE
        case handle_device_appearance:
            return HANDLE_DEVICE_APPEARANCE;
#endif
#ifdef HAVEDB_HANDLE_ROOT_TRANSFER_SERVICE
        case handle_root_transfer_service:
            return HANDLE_ROOT_TRANSFER_SERVICE;
#endif
#ifdef HAVEDB_HANDLE_GATT_SERVICE_CHANGED_CLIENT_CONFIG
        case handle_gatt_service_changed_client_config:
            return HANDLE_GATT_SERVICE_CHANGED_CLIENT_CONFIG;
#endif
#ifdef HAVEDB_HANDLE_MODEL_ID
        case handle_model_id:
            return HANDLE_MODEL_ID;
#endif
#ifdef HAVEDB_HANDLE_ROOT_TRANSFER_SERVICE_MIRROR_CONTROL_POINT_CLIENT_CONFIG
        case handle_root_transfer_service_mirror_control_point_client_config:
            return HANDLE_ROOT_TRANSFER_SERVICE_MIRROR_CONTROL_POINT_CLIENT_CONFIG;
#endif
#ifdef HAVEDB_HANDLE_ROOT_TRANSFER_SERVICE_FEATURES
        case handle_root_transfer_service_features:
            return HANDLE_ROOT_TRANSFER_SERVICE_FEATURES;
#endif
#ifdef HAVEDB_HANDLE_GAIA_DATA_CLIENT_CONFIG
        case handle_gaia_data_client_config:
            return HANDLE_GAIA_DATA_CLIENT_CONFIG;
#endif
#ifdef HAVEDB_HANDLE_ROLE_SELECTION_SERVICE_END
        case handle_role_selection_service_end:
            return HANDLE_ROLE_SELECTION_SERVICE_END;
#endif
#ifdef HAVEDB_HANDLE_DATA
        case handle_data:
            return HANDLE_DATA;
#endif
        default:
            break;
    }
    /* Check the GATT related conditional flags used to compile the ADK and the application. */
    /* The ADK just asked for an attribute value that the Application wasn't compiled for. */
    DEBUG_LOG("getGattAttributeValue lookup for id=%d(%x), n=%d failed", id, id, n);
    Panic();
    /* NOTREACHED */
    return 0;
}

