/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The tws_topology_twm_secondary rule table declarations. This file is generated by rulegen.py.
*/

#ifndef _TWS_TOPOLOGY_TWM_SECONDARY_RULES_TABLE_H__
#define _TWS_TOPOLOGY_TWM_SECONDARY_RULES_TABLE_H__

#include <rules_engine.h>
#include <tws_topology_common_secondary_rule_functions.h>
#include <tws_topology_rule_events.h>
#include <tws_topology_secondary_ruleset.h>
#include <tws_topology_goals.h>

/*! TWS Topology TWM rules deciding behaviour in a Secondary role. */
extern const size_t tws_topology_twm_secondary_rules_count;
extern const rule_entry_t tws_topology_twm_secondary_rules[];


#endif /* _TWS_TOPOLOGY_TWM_SECONDARY_RULES_TABLE_H__ */

