/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The dfu_peer_sig marshal type definitions. This file is generated by C:/Qualcomm_Prog/QCC514x_304x_Earbud/adk/tools/packages/typegen/typegen.py.
*/

#include <csrtypes.h>
#include <app/marshal/marshal_if.h>
#include <dfu_peer_sig_typedef.h>
#include <dfu_peer_sig_marshal_typedef.h>

const marshal_type_descriptor_t marshal_type_descriptor_dfu_peer_erase_req_res_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(dfu_peer_erase_req_res_t);
const marshal_type_descriptor_t marshal_type_descriptor_dfu_peer_device_not_in_use_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(dfu_peer_device_not_in_use_t);
const marshal_type_descriptor_t marshal_type_descriptor_dfu_peer_set_context_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(dfu_peer_set_context_t);


#define EXPAND_AS_TYPE_DEFINITION(type) (const marshal_type_descriptor_t *)&marshal_type_descriptor_##type,
const marshal_type_descriptor_t * const dfu_peer_sig_marshal_type_descriptors[] =
{
    DFU_PEER_SIG_MARSHAL_TYPES_TABLE(EXPAND_AS_TYPE_DEFINITION)
} ;

#undef EXPAND_AS_TYPE_DEFINITION

